name: Unit Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm
      - name: Run tests
        run: npm test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
